### ISSUE TITLE
python 3 detection problem on FreeBSD

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng#2264]
# syslog-ng

## Version of syslog-ng

3.17.2

## Platform

FreeBSD 11.2 amd64

# Issue

## Failure

Both Python 2.7 and 3.6 are installed on the machine. The configure script does not seem to find 3.6 even if configured to do so.
``
checking whether /usr/local/bin/python2.7 version is >= 3.6... no
configure: error: Python interpreter is too old
``
From config.log:
```
  $ ./configure --sysconfdir=/usr/local/etc --localstatedir=/var/db --enable-dynamic-linking --enable-manpages --disable-linux-caps --datadir=/usr/local/share/ --disable-amqp --with-libcurl=off --disable-geoip --disable-geoip2 --enable-ipv6 --disable-java --disable-java-modules --enable-json --disable-mongodb --with-python=3.6 --enable-python --disable-redis --without-libesmtp --disable-smtp --disable-spoof-source --disable-sql --disable-tcp-wrapper --prefix=/usr/local --mandir=/usr/local/man --disable-silent-rules --infodir=/usr/local/info/ --build=amd64-portbld-freebsd11.2
[...]
configure:14177: checking whether /usr/local/bin/python2.7 version is >= 3.6
configure:14188: /usr/local/bin/python2.7 -c import sys # split strings by '.' and convert to numeric. Append some zeros # because we need at least 4 digits for the hex conversion. # map returns an iterator in Python 3.0 and a list in 2.x minver = list(map(int, '3.6'.split('.'))) + [0, 0, 0] minverhex = 0 # xrange is not present in Python 3.0 and range returns an iterator for i in list(range(0, 4)): minverhex = (minverhex << 8) + minver[i] sys.exit(sys.hexversion < minverhex)
configure:14191: $? = 1
configure:14196: result: no
configure:14198: error: Python interpreter is too old
```
list of python executables:
```
root@fb112:~/syslog-ng317 # ls -l /usr/local/bin/python*
-r-xr-xr-x  1 root  wheel  5464 Jun 23 03:15 /usr/local/bin/python2.7
-r-xr-xr-x  1 root  wheel  1769 Jun 23 03:16 /usr/local/bin/python2.7-config
-r-xr-xr-x  2 root  wheel  7304 Sep  5 13:52 /usr/local/bin/python3.6
lrwxr-xr-x  1 root  wheel    17 Sep  5 13:52 /usr/local/bin/python3.6-config -> python3.6m-config
-r-xr-xr-x  2 root  wheel  7304 Sep  5 13:52 /usr/local/bin/python3.6m
-r-xr-xr-x  1 root  wheel  3119 Sep  5 13:52 /usr/local/bin/python3.6m-config
```

## Steps to reproduce

Run configure using:
```
./configure --enable-python --with-python=3.6
```

**Comment by gaborznagy** [comment]
It is working on xenial.
On FreeBSD I have reproduced the problem with python-3.6 and it is working with python-2.7.
It is strange that pkg-config "sees" the 3.6 version too:
```
$pkg-config --list-all | grep python
python-3.6m           Python - Python library
python-3.6            Python - Python library
python-2.7            Python - Python library
```
It should be working according to configure:
```
    case "$with_python" in                                                                                             │Unknown option --varaible=pcfiledir
      [[0-9]])                                                                                                         │gabornagy@gaborzbot:~/work/syslog-ng-OSE$ pkg-config --variable=pcfiledir python2                                     
          with_python="python${with_python}"                                                                           │/usr/lib/x86_64-linux-gnu/pkgconfig
          ;;                                                                                                           │gabornagy@gaborzbot:~/work/syslog-ng-OSE$ pkg-config --variable=pcfiledir python
      [[0-9]].[[0-9]])                                                                                                 │/usr/lib/x86_64-linux-gnu/pkgconfig
          with_python="python-${with_python}"                                                                          │gabornagy@gaborzbot:~/work/syslog-ng-OSE$ pkg-config --variable=pcfiledir python-2.7
          ;;                                                                                                           │/usr/lib/x86_64-linux-gnu/pkgconfig
    esac                                                                                                               │gabornagy@gaborzbot:~/work/syslog-ng-OSE$ ll /usr/lib/x86_64-linux-gnu/pkgconfig/*python*                             
                                                                                                                       │-rw-r--r-- 1 root root 263 Dec  4  2017 /usr/lib/x86_64-linux-gnu/pkgconfig/python-2.7.pc
    PKG_CHECK_MODULES(PYTHON, $with_python, python_found="yes", python_found="no")  
```

**Comment by bazsi** [comment]
The configure snippet  and the output of some commands are a bit mingled.

I have noticed that there's a --varaible instead of variable.

Also, pkg-config might be too old, and doesnt recognize an option?

**Comment by czanik** [comment]
syslog-ng source as is still can't find anything other than Python 2 on FreeBSD. On the other hand with some ports Makefile magic I am able to compile syslog-ng in ports with Python 3.6

From my part finding a proper solution is no more urgent, as the vast majority of FreeBSD users use ports/packages. Of course if there is anything I can help in resolving the issue, I am ready to help any time.

**Comment by Kokan** [comment]
Sharing that magic could be a first step :)

**Comment by czanik** [comment]
First I only changed the PYTHON_CONFIGURE_* parameters from 2.7 to 3.6, had the correct configure parameters, but compilation still failed.

Changing the USES variable solved the problem without any visible changed to ./configure parameters.
I guess the file list at the end could be more elegant, and as a next step I'll try to make the Python version configurable. 

```
root@fb112:~ # diff -u syslog-ng317.old/Makefile syslog-ng317/Makefile
--- syslog-ng317.old/Makefile	2018-08-15 22:15:29.000000000 +0200
+++ syslog-ng317/Makefile	2018-09-27 14:30:09.816684000 +0200
@@ -38,16 +38,16 @@
 REDIS_DESC=		Build with Redis support
 JAVA_DESC=		Build with Java support (no modules)
 JAVA_MOD_DESC=		Build with Java modules (needs Maven / Internet access)
-PYTHON_DESC=		Build with Python 2.7 support
+PYTHON_DESC=		Build with Python 3.6 support
 CURL_DESC=		Build with Curl HTTP support
 AMQP_DESC=		Build with AMQP support
 
 USES=		autoreconf:build gmake libtool pathfix pkgconfig ssl \
-		gettext-runtime python:build shebangfix
+		gettext-runtime python:3.6,build shebangfix
 USE_LDCONFIG=	yes
 USE_RC_SUBR=	syslog-ng
 SHEBANG_FILES=	lib/merge-grammar.py
-SHEBANG_LANG=	python
+SHEBANG_LANG=	python3
 GNU_CONFIGURE=	yes
 USE_GNOME=	glib20
 SUB_FILES=	pkg-message
@@ -143,48 +143,48 @@
 				lib/syslog-ng/java-modules/syslog-ng-common.jar
 
 PYTHON_CONFIGURE_ON=		--enable-python
-PYTHON_CONFIGURE_OFF=		--disable-python --with-python=2.7
-PYTHON_CONFIGURE_WITH=		python=2.7
+PYTHON_CONFIGURE_OFF=		--disable-python --with-python=3.6
+PYTHON_CONFIGURE_WITH=		python=3.6
 PYTHON_PLIST_FILES=		lib/syslog-ng/libmod-python.so \
                    %%PYTHON_SITELIBDIR%%/syslogng-1.0-py%%PYTHON_VER%%.egg-info \
                    %%PYTHON_SITELIBDIR%%/syslogng/__init__.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/__init__.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/__pycache__/__init__.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__init__.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__init__.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/__init__.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/choicecompleter.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/choicecompleter.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/choicecompleter.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/commandlinelexer.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/commandlinelexer.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/commandlinelexer.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/completer.py  \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/completer.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/completer.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/completerlang.py  \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/completerlang.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/completerlang.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/debuggercli.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/debuggercli.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/debuggercli.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/debuglang.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/debuglang.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/debuglang.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/getoptlexer.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/getoptlexer.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/getoptlexer.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/langcompleter.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/langcompleter.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/langcompleter.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/lexer.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/lexer.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/lexer.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/lexertoken.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/lexertoken.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/lexertoken.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/macrocompleter.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/macrocompleter.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/macrocompleter.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/readline.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/readline.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/readline.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/syslognginternals.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/syslognginternals.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/syslognginternals.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/tablexer.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/tablexer.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/tablexer.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/templatelang.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/templatelang.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/templatelang.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/templatelexer.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/templatelexer.pyc \
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/templatelexer.cpython-36.pyc \
                    %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/tflang.py \
-                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/tflang.pyc
+                   %%PYTHON_SITELIBDIR%%/syslogng/debuggercli/__pycache__/tflang.cpython-36.pyc
 
 CURL_CONFIGURE_OFF=		--with-libcurl=off
 CURL_LIB_DEPENDS=		libcurl.so:ftp/curl
root@fb112:~ # 
```

**Comment by Kokan** [comment]
@czanik could you please check if it works with latest master ?

**Comment by czanik** [comment]
Yes. It seems to work now.
