### ISSUE TITLE
Syslog-ng version 3.17.2 - Memory Leak in 

### ISSUE THREAD

**Issue by HanouaJ** [balabit/syslog-ng#2380]
# syslog-ng

## Version of syslog-ng
syslog-ng 3 (3.17.2)
Config version: 3.17
Installer-Version: 3.17.2
Revision:
Compile-Date: Aug 14 2018 07:21:10
Module-Directory: //usr/lib64/syslog-ng
Module-Path: //usr/lib64/syslog-ng
Available-Modules: add-contextual-data,afamqp,affile,afprog,afsocket,afstomp,afuser,appmodel,basicfuncs,cef,confgen,cryptofuncs,csvparser,date,dbparser,disk-buffer,graphite,hook-commands,json-plugin,kvformat,linux-kmsg-format,map-value-pairs,pseudofile,sdjournal,snmptrapd-parser,stardate,syslogformat,system-source,tags-parser,tfgetent,xml,redis,http
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on

## Platform

CentOS Linux release 7.5.1804 (Core)

## Debug bundle

Syslog-NG DEBUg buNdle generator
Start environment detection
Linux-type FHS detected
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.5.1804 (Core)
Release:        7.5.1804
Codename:       Core

Operating System Name: Linux

Redhat specific checks
Check package files integrity
package syslog-ng-premium-edition is not installed
package syslog-ng-premium-edition-client is not installed
package syslog-ng-premium-edition-compact is not installed
No syslog-ng RPM packages have been found!
list syslog-related packages

Start general info collection
System's full uname: Linux p-syslogng 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Getting network-interface information: Success
Getting network routes: Success
Getting DNS resolution-related information: Done
List all processes
Mount and disk free info collection

Start Syslog-specific info collection
Copy configs from /etc/syslog-ng
9 blocks
Gathering PKI information... done.
cat: /var/lib/syslog-ng/syslog-ng.pid: No such file or directory
SVpid:  SNGpid:  Chpids:
Syslog-ng's exact version: syslog-ng 3 (3.17.2)
/usr/sbin/syslog-ng-ctl stats
/usr/sbin/syslog-ng-ctl query get *
/usr/sbin/syslog-ng-ctl show-license-info
/usr/sbin/syslog-ng-ctl credentials status
32 blocks
Detecting init system: systemd detected...
Generating second batch of statistics
/usr/sbin/syslog-ng-ctl stats
/usr/sbin/syslog-ng-ctl query get *

Generating hashes... done.
Debug Bundle generation: Done.
tar: ./var/syslog-ng.ctl: socket ignored
Terminating live message watcher: /sbin/syslog-ng-debun: line 273:  5844 Terminated              tail -f ${tmpdir}/syslog-ng.debun.txt 1>&3  (wd: /home/user)

Your debug bundle will be stored at /tmp/syslog.debun.p-syslogng.2018-10-29_14-40.5836.tgz

# Issue
Syslog-ng is never freeing the memory it has used while queuing messages prior to their delivery to redis (via the syslog-ng redis module), and syslog-ng continues consuming more memory until it gets shutdown by the OS when there is no more free memory left.

When using the stats command, it is clear that there is no messages being queued but still the syslog-ng process is occupying gigabytes of RAM, and these gigabytes of RAM will stay used by syslog-ng forever unless syslog-ng is restarted.

**$ sudo syslog-ng-ctl stats**

SourceName;SourceId;SourceInstance;State;Type;Number
center;;received;a;processed;7547577
destination;d_redis1;;a;processed;3773787
destination;d_redis2;;a;processed;3773790
center;;queued;a;processed;7547577
global;scratch_buffers_count;;a;queued;2
global;payload_reallocs;;a;processed;44
global;sdata_updates;;a;processed;0
global;scratch_buffers_bytes;;a;queued;512
dst.redis;d_redis1#0;redis,p-redis1.mg.prod.aws,6379;a;dropped;0
dst.redis;d_redis1#0;redis,p-redis1.mg.prod.aws,6379;a;processed;3773787
dst.redis;d_redis1#0;redis,p-redis1.mg.prod.aws,6379;a;queued;1
dst.redis;d_redis1#0;redis,p-redis1.mg.prod.aws,6379;a;written;3773785
dst.redis;d_redis2#0;redis,p-redis2.mg.prod.aws,6379;a;dropped;0
dst.redis;d_redis2#0;redis,p-redis2.mg.prod.aws,6379;a;processed;3773790
dst.redis;d_redis2#0;redis,p-redis2.mg.prod.aws,6379;a;queued;2
dst.redis;d_redis2#0;redis,p-redis2.mg.prod.aws,6379;a;written;3773787
global;msg_clones;;a;processed;0
source;input_udp;;a;processed;7547577

## Configuration
**$ cat /etc/syslog-ng/syslog-ng.conf**
@version:3.17
options {
    create_dirs (no);
    flush_lines (100);
    chain_hostnames (off);
    use_dns (no);
    keep_hostname (yes);
    use_fqdn (no);
    log_fifo_size (1200000);
    time_reopen (10);
};
@include "/etc/syslog-ng/conf.d/logs.conf"

**$ cat /etc/syslog-ng/conf.d/logs.conf**
options { use_uniqid (yes); };
source input_udp { udp(ip(0.0.0.0) port(1514) log_msg_size(65536));};

destination d_redis1 {
  redis(
    host("redis1.mg.prod.aws")
   command("lpush" "nxlist" "${MSG}")
  );
};

filter filter1 {
  "$(% ${RCPTID} 2)"  eq "0"
};

log {
  source(input_udp);
  filter(filter1);
  destination(d_redis1);
};

destination d_redis2 {
  redis(
    host("redis2.mg.prod.aws")
   command("lpush" "nxlist" "${MSG}")
  );
};

filter filter2 {
  "$(% ${RCPTID} 2)"  eq "1"
};

log {
  source(input_udp);
  filter(filter2);
  destination(d_redis2);
};

**Comment by Kokan** [comment]
@HanouaJ hello, I tried to check this leak, but cannot find per message leak in case of redis destination.
I also tried to let the queue store some item, and start redis after some messages.

But I've found a connection related leak, it leaks every time it reconnects, or when you reload syslog-ng. Soon I'll send a PR for that.

Could you test it with `valgrind` ? to determine where the actual leak is

**Comment by HanouaJ** [comment]
Hi Kokan, thank you for your feed-back. I will do both tests and get back to you as soon as I can :)

**Comment by HanouaJ** [comment]
Hello Kokan ! Here is the output of two tests using Valgrind from our DEV environment with the same configuration I have mentioned before (Without the new PR fix that you made) :

**# valgrind --leak-check=yes /usr/sbin/syslog-ng -F -p /var/run/syslogd.pid**
```
==20827== Memcheck, a memory error detector
==20827== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==20827== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==20827== Command: /usr/sbin/syslog-ng -F -p /var/run/syslogd.pid
==20827==
[2018-10-30T15:39:55.697079] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
==20827==
==20827== HEAP SUMMARY:
==20827==     in use at exit: 39,327 bytes in 125 blocks
==20827==   total heap usage: 31,659,335 allocs, 31,659,210 frees, 7,137,450,402 bytes allocated
==20827==
==20827== 16 bytes in 2 blocks are definitely lost in loss record 21 of 72
==20827==    at 0x4C29C23: malloc (vg_replace_malloc.c:299)
==20827==    by 0x596DF6D: g_malloc (in /usr/lib64/libglib-2.0.so.0.5400.2)
==20827==    by 0x59852CD: g_slice_alloc (in /usr/lib64/libglib-2.0.so.0.5400.2)
==20827==    by 0x593B68A: g_mutex_new (in /usr/lib64/libglib-2.0.so.0.5400.2)
==20827==    by 0x593B9A4: g_static_mutex_get_mutex_impl (in /usr/lib64/libglib-2.0.so.0.5400.2)
==20827==    by 0x4E80287: main_loop_call (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x4E80885: ??? (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x598F984: ??? (in /usr/lib64/libglib-2.0.so.0.5400.2)
==20827==    by 0x68B9E24: start_thread (in /usr/lib64/libpthread-2.17.so)
==20827==    by 0x6BCCBAC: clone (in /usr/lib64/libc-2.17.so)
==20827==
==20827== 168 bytes in 1 blocks are possibly lost in loss record 59 of 72
==20827==    at 0x4C29C23: malloc (vg_replace_malloc.c:299)
==20827==    by 0x66AAEB0: iv_work_pool_create (in /usr/lib64/libivykis.so.0.3.5)
==20827==    by 0x4E80CC5: main_loop_io_worker_init (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x4E7FBF3: main_loop_init (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x401951: main (in /usr/sbin/syslog-ng)
==20827==
==20827== 588 (336 direct, 252 indirect) bytes in 3 blocks are definitely lost in loss record 60 of 72
==20827==    at 0x4C2B9B5: calloc (vg_replace_malloc.c:711)
==20827==    by 0x596DFC5: g_malloc0 (in /usr/lib64/libglib-2.0.so.0.5400.2)
==20827==    by 0x4EA4B63: log_template_new (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0xAE12FD8: redis_parse (in /usr/lib64/syslog-ng/libredis.so)
==20827==    by 0x4E6C262: cfg_parser_parse (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x4E83DFE: plugin_construct_from_config (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x4E67F55: cfg_parse_plugin (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x4E91C58: main_parse (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x4E6C262: cfg_parser_parse (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x4E68652: cfg_run_parser (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x4E6877E: cfg_read_config (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x4E7FDC5: main_loop_read_and_init_config (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==
==20827== 688 bytes in 1 blocks are possibly lost in loss record 61 of 72
==20827==    at 0x4C2B9B5: calloc (vg_replace_malloc.c:711)
==20827==    by 0x40128C4: _dl_allocate_tls (in /usr/lib64/ld-2.17.so)
==20827==    by 0x68BA7FB: pthread_create@@GLIBC_2.2.5 (in /usr/lib64/libpthread-2.17.so)
==20827==    by 0x66AD3F7: iv_thread_create (in /usr/lib64/libivykis.so.0.3.5)
==20827==    by 0x66AAE53: ??? (in /usr/lib64/libivykis.so.0.3.5)
==20827==    by 0x66AB0A8: iv_work_pool_submit_work (in /usr/lib64/libivykis.so.0.3.5)
==20827==    by 0x66AB80F: ??? (in /usr/lib64/libivykis.so.0.3.5)
==20827==    by 0x66AC7D3: iv_main (in /usr/lib64/libivykis.so.0.3.5)
==20827==    by 0x4E7FFF5: main_loop_run (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x4019A9: main (in /usr/sbin/syslog-ng)
==20827==
==20827== 2,180 (200 direct, 1,980 indirect) bytes in 1 blocks are definitely lost in loss record 69 of 72
==20827==    at 0x4C29C23: malloc (vg_replace_malloc.c:299)
==20827==    by 0x596DF6D: g_malloc (in /usr/lib64/libglib-2.0.so.0.5400.2)
==20827==    by 0x4E71285: g_process_set_argv_space (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==20827==    by 0x4017D7: main (in /usr/sbin/syslog-ng)
==20827==
==20827== LEAK SUMMARY:
==20827==    definitely lost: 552 bytes in 6 blocks
==20827==    indirectly lost: 2,232 bytes in 36 blocks
==20827==      possibly lost: 856 bytes in 2 blocks
==20827==    still reachable: 35,687 bytes in 81 blocks
==20827==         suppressed: 0 bytes in 0 blocks
==20827== Reachable blocks (those to which a pointer was found) are not shown.
==20827== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==20827==
==20827== For counts of detected and suppressed errors, rerun with: -v
==20827== ERROR SUMMARY: 5 errors from 5 contexts (suppressed: 0 from 0)
```




**# valgrind --leak-check=full /usr/sbin/syslog-ng -F -p /var/run/syslogd.pid**
```
==28484== Memcheck, a memory error detector
==28484== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==28484== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==28484== Command: /usr/sbin/syslog-ng -F -p /var/run/syslogd.pid
==28484==
[2018-10-30T16:39:25.832850] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
==28484==
==28484== HEAP SUMMARY:
==28484==     in use at exit: 107,435 bytes in 136 blocks
==28484==   total heap usage: 571,956 allocs, 571,820 frees, 131,058,138 bytes allocated
==28484==
==28484== 16 bytes in 2 blocks are definitely lost in loss record 24 of 83
==28484==    at 0x4C29C23: malloc (vg_replace_malloc.c:299)
==28484==    by 0x596DF6D: g_malloc (in /usr/lib64/libglib-2.0.so.0.5400.2)
==28484==    by 0x59852CD: g_slice_alloc (in /usr/lib64/libglib-2.0.so.0.5400.2)
==28484==    by 0x593B68A: g_mutex_new (in /usr/lib64/libglib-2.0.so.0.5400.2)
==28484==    by 0x593B9A4: g_static_mutex_get_mutex_impl (in /usr/lib64/libglib-2.0.so.0.5400.2)
==28484==    by 0x4E80287: main_loop_call (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4E80885: ??? (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x598F984: ??? (in /usr/lib64/libglib-2.0.so.0.5400.2)
==28484==    by 0x68B9E24: start_thread (in /usr/lib64/libpthread-2.17.so)
==28484==    by 0x6BCCBAC: clone (in /usr/lib64/libc-2.17.so)
==28484==
==28484== 168 bytes in 1 blocks are possibly lost in loss record 65 of 83
==28484==    at 0x4C29C23: malloc (vg_replace_malloc.c:299)
==28484==    by 0x66AAEB0: iv_work_pool_create (in /usr/lib64/libivykis.so.0.3.5)
==28484==    by 0x4E80CC5: main_loop_io_worker_init (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4E7FBF3: main_loop_init (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x401951: main (in /usr/sbin/syslog-ng)
==28484==
==28484== 588 (336 direct, 252 indirect) bytes in 3 blocks are definitely lost in loss record 68 of 83
==28484==    at 0x4C2B9B5: calloc (vg_replace_malloc.c:711)
==28484==    by 0x596DFC5: g_malloc0 (in /usr/lib64/libglib-2.0.so.0.5400.2)
==28484==    by 0x4EA4B63: log_template_new (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0xAE12FD8: redis_parse (in /usr/lib64/syslog-ng/libredis.so)
==28484==    by 0x4E6C262: cfg_parser_parse (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4E83DFE: plugin_construct_from_config (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4E67F55: cfg_parse_plugin (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4E91C58: main_parse (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4E6C262: cfg_parser_parse (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4E68652: cfg_run_parser (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4E6877E: cfg_read_config (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4E7FDC5: main_loop_read_and_init_config (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==
==28484== 688 bytes in 1 blocks are possibly lost in loss record 70 of 83
==28484==    at 0x4C2B9B5: calloc (vg_replace_malloc.c:711)
==28484==    by 0x40128C4: _dl_allocate_tls (in /usr/lib64/ld-2.17.so)
==28484==    by 0x68BA7FB: pthread_create@@GLIBC_2.2.5 (in /usr/lib64/libpthread-2.17.so)
==28484==    by 0x66AD3F7: iv_thread_create (in /usr/lib64/libivykis.so.0.3.5)
==28484==    by 0x66AAE53: ??? (in /usr/lib64/libivykis.so.0.3.5)
==28484==    by 0x66AB0A8: iv_work_pool_submit_work (in /usr/lib64/libivykis.so.0.3.5)
==28484==    by 0x66AB80F: ??? (in /usr/lib64/libivykis.so.0.3.5)
==28484==    by 0x66AC7D3: iv_main (in /usr/lib64/libivykis.so.0.3.5)
==28484==    by 0x4E7FFF5: main_loop_run (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4019A9: main (in /usr/sbin/syslog-ng)
==28484==
==28484== 2,180 (200 direct, 1,980 indirect) bytes in 1 blocks are definitely lost in loss record 78 of 83
==28484==    at 0x4C29C23: malloc (vg_replace_malloc.c:299)
==28484==    by 0x596DF6D: g_malloc (in /usr/lib64/libglib-2.0.so.0.5400.2)
==28484==    by 0x4E71285: g_process_set_argv_space (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4017D7: main (in /usr/sbin/syslog-ng)
==28484==
==28484== 68,108 (1,224 direct, 66,884 indirect) bytes in 1 blocks are definitely lost in loss record 83 of 83
==28484==    at 0x4C2B9B5: calloc (vg_replace_malloc.c:711)
==28484==    by 0x596DFC5: g_malloc0 (in /usr/lib64/libglib-2.0.so.0.5400.2)
==28484==    by 0x4E98883: log_proto_dgram_server_new (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0xA7CFC42: ??? (in /usr/lib64/syslog-ng/libafsocket.so)
==28484==    by 0xA7D02E5: ??? (in /usr/lib64/syslog-ng/libafsocket.so)
==28484==    by 0xA7D0B9B: afsocket_sd_init_method (in /usr/lib64/syslog-ng/libafsocket.so)
==28484==    by 0xA7D23C8: afinet_sd_init (in /usr/lib64/syslog-ng/libafsocket.so)
==28484==    by 0x4E6DDE4: cfg_tree_start (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4E68102: cfg_init (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4E7FB67: main_loop_initialize_state (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x4E7FE10: main_loop_read_and_init_config (in /usr/lib64/libsyslog-ng-3.17.so.0.0.0)
==28484==    by 0x401959: main (in /usr/sbin/syslog-ng)
==28484==
==28484== LEAK SUMMARY:
==28484==    definitely lost: 1,776 bytes in 7 blocks
==28484==    indirectly lost: 69,116 bytes in 46 blocks
==28484==      possibly lost: 856 bytes in 2 blocks
==28484==    still reachable: 35,687 bytes in 81 blocks
==28484==         suppressed: 0 bytes in 0 blocks
==28484== Reachable blocks (those to which a pointer was found) are not shown.
==28484== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==28484==
==28484== For counts of detected and suppressed errors, rerun with: -v
==28484== ERROR SUMMARY: 6 errors from 6 contexts (suppressed: 0 from 0)

```

**Comment by Kokan** [comment]
@HanouaJ those are not the leak that I've fixed with my PR.
Those leaks does not seem to be per message leak, but rather per configuration parsing, based on your issue I assumed you have per message leak (that kind of leak I did not found).
Because of these leaks, your memory usage should not raise if you do not reload.

* Do you do syslog-ng reload often ?
* Do you think there is per message/event leak ?

**Comment by HanouaJ** [comment]
@Kokan 

> Do you do syslog-ng reload often ?
Reloading syslog-ng doesn't solve the problem and doesn't free the memory at all, only restarting does but as as we receive tens of thousands of logs per second, restarting might cause an important log data loss.

> Do you think there is per message/event leak ?
Honestly, I have no clue.

**Comment by HanouaJ** [comment]
We rarely reload syslog-ng, so reloading shouldn't be the cause of this leak.

I am able to produce this issue using a Syslog-ng version 3.17.2, with the same configuration I have mentioned, that pushes messages to two Redis servers with the syslog-ng's redis module (the same configuration I have mentioned in my first post), the memory leak occurs not matter what messages rate we use, except that with high message rates the RAM will get saturated rapidly. Usually we are around 5K message/second, during peak times we reach 20-40K message/s

I have been able to reproduce this problem with loggen, I launched the following command for few seconds that increased syslog-ng memory usage, and waited for all the messages to get pushed to Redis and for syslog-ng queues to get emptied, and at the end I can still see that the memory usage never dropped back. 
**$ loggen --inet --dgram --size 300 --rate 25000 --interval 600 127.0.0.1 1514**

Having a look at both redis and syslog-ng machines, the number of connections seem so stable and limited to less than 10 connections per each server.

**Comment by Kokan** [comment]
Okay, I'll give it an other go to reproduce it, seems straight forward. (I did not use your exact config.)

**Comment by HanouaJ** [comment]
@Kokan Thank you, that's very clear. I wasn't aware that log-msg-size defaults to 65536 bytes (which is a big value to my opinion), so I am reducing its value along with the log-fifo-size. Will get back to you with feed-back.

**Comment by Kokan** [comment]
@HanouaJ 
The `65536` is default value in 3.17.2, but in your configuration file, you also specified that amount:
```
source input_udp { udp(ip(0.0.0.0) port(1514) log_msg_size(65536));};
```
The original was 8k, and that was too small for common logs: https://github.com/balabit/syslog-ng/pull/1412
Maybe this is a large value, but it is hard to say either way without data; and luckily it is possible to change.

Would you mind closing this issue ?

**Comment by HanouaJ** [comment]
Now I know where was my confusion was, the log-fifo-size is applied to each queue that is created by syslog-ng and as I have two destinations (two redis outputs) then syslog-ng creates two queues and then it might reach a total of 2 x 1200000 messages accumulated in the RAM, which we don't intend to. Moreover, your explanation about the memory caching of syslog-ng helped me understand that it's not really a memory leak but it's just that syslog-ng is allocating all the memory it needs and not freeing it immediately  even if all the messages are processed and the queues are all empty.

Many thanks.
Closing the issue.
