### ISSUE TITLE
syslog-ng (3.9.1) opens log files multiple times and/or keeps deleted files opened

### ISSUE THREAD

**Issue by mikeBashStuff** [balabit/syslog-ng#2733]
## Version of syslog-ng

```
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 
Module-Directory: /usr/lib/syslog-ng
Module-Path: /usr/lib/syslog-ng
Available-Modules: afsocket,disk-buffer,afamqp,csvparser,linux-kmsg-format,graphite,syslogformat,afuser,basicfuncs,kvformat,confgen,cef,cryptofuncs,pseudofile,afprog,sdjournal,system-source,add-contextual-data,afstomp,affile,date,dbparser
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
```
Compilation config:
```
./configure \
                --enable-ipv6 \
                --prefix=/usr \
                --sysconfdir=/etc/syslog-ng \
                --localstatedir=/var/run/syslog-ng \
                --disable-linux-caps \
                --disable-java \
                --disable-python \
                --with-mongoc=no \
                --enable-mongodb=no \
                --with-default-modules=affile,afprog,afsocket,afuser,basicfuncs,csvparser,syslogformat
```
## Platform

OS: Linux (embedded distro)
Kernel version: 4.4.88

# Issue
Recently there's been noticed a quite peculiar behavior that happens at some point during the log files rotation. From the look of it, syslog-ng either ends up with some fds still pointing at files that were already deleted|moved and/or allocates additional fds pointing at the same file. This issue usually surfaces when syslog-ng is under heavy pressure (plenty of threads spinning at the same time).

The expected is to see this:
```
# get_open_files $(</var/service/syslog-ng/supervise/pid) messages
30->/var/log/messages
# get_open_files $(</var/service/syslog-ng/supervise/pid) vmstat.log
28->/var/log/packetlogic/vmstat.log
# and so on, single fd for each log file
```
However, after some time, something like this can be seen:
```
# get_open_files $(</var/service/syslog-ng/supervise/pid) messages
123->/var/log/messages
141->/var/log/messages
30->/var/log/messages.1 (deleted)
# get_open_files $(</var/service/syslog-ng/supervise/pid) debug   
114->/var/log/debug
122->/var/log/debug
44->/var/log/debug.1 (deleted)
```
The rotation in question is done by newsyslog which is executed by crond every minute. The snippet of its config looks like so:
```
# Format:
# log_filename [owner:group] mode count kb hrs/at [flgs][/pid_file][sig]

/var/log/messages                     644 5 2000  * Z0 USR1
/var/log/debug                        644 5 10000 * DZ0 USR1
....
```
If given log file reaches the threshold of allowed size, newsyslog will move it to e.g. /var/log/messages.0. If messages.0 already exists, it will be moved to messages.1 and then gzip would be  forked to compress the file into messages.1.gz (this is repeated up to *5.gz files). As the last step, newsyslog sends USR1 to syslog-ng to re-open all the log files. Now, from the output above, it looks like something goes wrong with handling the actual signal, since syslog-ng still references *.1 file which was already deleted (compressed into *.1.gz). I can't say if syslog-ng is at fault here or newsyslog, however, when HUP is used instead of USR1 (as we did before USR1 handler was introduced) this issue is not seen (or at least it can't be reproduced). 

As to the additional fd being opened for the same file, I have no idea why that happens. In time, after newsyslog is forced to rotate files, it gets worse. Examples extreme of cases:
```
# get_open_files $(</var/service/syslog-ng/supervise/pid) messages
141->/var/log/messages.1 (deleted)
143->/var/log/messages.1 (deleted)
153->/var/log/messages.0
158->/var/log/messages.1 (deleted)
178->/var/log/messages.1 (deleted)
26->/var/log/messages
30->/var/log/messages.1 (deleted)
64->/var/log/messages.1 (deleted)
83->/var/log/messages.1 (deleted)
# get_open_files $(</var/service/syslog-ng/supervise/pid) debug   
105->/var/log/debug.1 (deleted)
114->/var/log/debug.1 (deleted)
120->/var/log/debug.1 (deleted)
156->/var/log/debug.0
199->/var/log/debug.0
217->/var/log/debug.0
238->/var/log/debug.0
33->/var/log/debug
44->/var/log/debug.1 (deleted)
51->/var/log/debug.1 (deleted)
52->/var/log/debug.1 (deleted)
58->/var/log/debug.1 (deleted)
61->/var/log/debug.1 (deleted)
80->/var/log/debug.1 (deleted)
82->/var/log/debug.1 (deleted)
97->/var/log/debug.1 (deleted)
```
Since 3.9.1 is "a bit" behind, any links to patches or versions that could include potential fix would be appreciated (there was a plan to upgrade our syslog-ng to 3.18.1 but due to https://github.com/balabit/syslog-ng/issues/2457 it's been postponed).

## Configuration
```
@version: 3.9
options {
    # Wait for 10 lines or 1 second before writing to disk
    flush_lines(10); flush_timeout(1000);
    log_msg_size(2048);
    stats_freq(86400);
    create_dirs(yes);
    use_dns(persist_only);
    keep_hostname(yes);
    keep_timestamp(no);
    frac_digits(3);
    time-reopen(5);
};

source src {
    file("/proc/kmsg" program_override("kernel"));
    unix-stream("/dev/log");
    internal();
    udp(ip("127.0.0.1") host_override("`HOSTNAME`"));
};

template t_syslogd { template("$ISODATE $HOST $MSGHDR$MSG\n"); template_escape(no); };
template t_remote { template("<$PRI>$DATE $HOST $MSGHDR$MSG\n"); template_escape(no); };
template t_onlymsg { template("$MSG\n"); template_escape(no); };


filter f_auth { facility(auth); };
filter f_authpriv { facility(authpriv); };
filter f_kern { facility(kern); };
filter f_python { facility(local2); };
filter f_everything { level(info..emerg); };
filter f_emerg { level(emerg); };
filter f_alert { level(alert); };
filter f_crit { level(crit); };
filter f_err { level(err); };
filter f_warning { level(warn); };
filter f_notice { level(notice); };
filter f_info { level(info); };
filter f_notdebug { not level(debug); };

filter f_vmstat { program("^vmstat$"); };
filter f_postgresql { program("^postgres$"); };
filter f_dockerd { program("^dockerd"); };
filter f_docker { program("^docker$"); };
filter f_vmtools {
    program("^vmsvc$") or
    program("^toolboxcmd$") or
    program("^vmtoolsd$");
};
filter f_ipmievd { program("^ipmievd$"); };

#Activate on disk logging
@include "/etc/syslog-ng/ondisk"

# Read user configured syslog receivers
@include "/etc/syslog-ng/remotes/"
@include "/etc/syslog-ng/options/"
```

**Comment by furiel** [comment]
I was fighting with a similar issue. My guess is it is fixed by https://github.com/balabit/syslog-ng/pull/2434.

**Comment by Kokan** [comment]
I could reproduce something similuar on current master with the following config (default + msg generator):

```
#############################################################################
# Default syslog-ng.conf file which collects all local logs into a
# single file called /var/log/messages.
#

@version: 3.21
@include "scl.conf"

source s_local {
        system();
        internal();
example-msg-generator(freq(0.0000001));
};

source s_network {
        default-network-drivers(
                # NOTE: TLS support
                #
                # the default-network-drivers() source driver opens the TLS
                # enabled ports as well, however without an actual key/cert
                # pair they will not operate and syslog-ng would display a
                # warning at startup.
                #
                #tls(key-file("/path/to/ssl-private-key") cert-file("/path/to/ssl-cert"))
        );
};

destination d_local {
        file("/tmp/messages");
        file("/tmp/messages-kv.log" template("$ISODATE $HOST $(format-welf --scope all-nv-pairs)\n") frac-digits(3));
};

log {
        source(s_local);

        # uncomment this line to open port 514 to receive messages
        #source(s_network);
        destination(d_local);
};
```

Just running: `watch -n.1 'syslog-ng-ctl reopen`, the number of opened `/tmp/messages` keept increasing, but not even reload reduced it.

**Comment by mikeBashStuff** [comment]
Tried to use commits from https://github.com/balabit/syslog-ng/pull/2434 (patches were applied cleanly to our 3.9.1 build), however, issue still remains. 

I didn't mention it initially, but this also introduces a memory leak (I am not sure if this is purely because of the increasing amount of fds or if there's an additional issue somewhere, but while reproducing the whole thing it's seen that memory allocation for syslog-ng steadily increases).

**Comment by Kokan** [comment]
Thanks for testing with #2434, my guess based on the initial test that both memory and fd leak origin is the same, there is a race while reopening files and doing processing in other threads. But could not dig deeper.

Note:
I plan to work on this issue right after creating a PR for fixing deadlock in groupby parser.

**Comment by mikeBashStuff** [comment]
Any chance we can move this ticket forward any time soon? I am afraid it's quite critical on our end to get this fixed since it affects our production quite heavily. Basically, the amount of opened fds uses entire space on the partition where the logs are kept (which affects other components that need to write to it so syslog-ng needs to be periodically restarted to free up the space) and the actual memory leak sooner or later leads to kernel OOMing causing a bit of a havoc. 

Considering all that, any feedback would be appreciated.

**Comment by mikeBashStuff** [comment]
Issue still present in 3.23.1 release.

**Comment by Kokan** [comment]
Does using the `reload` instead of `reopen` acceptable for you ? With `reload` I cannot reproduce the same issue (that has a sync step and reopen does not).

**Comment by mikeBashStuff** [comment]
@Kokan I think it would be ok. I mean, we decided to start using USR1 instead of HUP to avoid https://github.com/balabit/syslog-ng/issues/1423 in our 3.9.1 build, but since https://github.com/balabit/syslog-ng/pull/1709 fixes it then I guess we could finally upgrade to the latest version and go back to using HUP|reload until this issue is fixed.
