### ISSUE TITLE
3.6.2 consumes all available memory over a few hours

### ISSUE THREAD

**Issue by elentar** [balabit/syslog-ng#446]
I have a number of servers running RHEL 6, using the RedHat-provided syslog-ng 3.2 to provide syslog archive functionality. I would like to take advantage of threading support, so I've been looking at upgrading to a newer build of syslog-ng. I happened upon syslog-ng 3.6.2 packages available here:

https://copr-be.cloud.fedoraproject.org/results/czanik/syslog-ng36epel6/epel-6-x86_64/

These packages installed easily, requiring only the json-c and riemann-c-client packages as dependencies. I modified my running config to address the issues reported by the configcheck and started using 3.6.2.

I've observed that over about 12 hours the process consumes all available memory on the server. If I split the traffic across multiple servers, the rate of memory consumption decreases accordingly, so it appears to be a function of the message volume.

During the 12-hour incident, the message volume was approximately 4,500 messages per second. Around 48GB of memory was consumed during this test.

During a 48-hour test, at a rate of 500 messages per second, 20GB of memory was consumed.

I will attach a sanitized config file shortly.

**Comment by elentar** [comment]
```
@version:3.6

# vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:

#################################################################
# syslog-ng configuration file.
#
# global options
#
# See syslog-ng(8) and syslog-ng.conf(5) for more information.
#

options {
    flush_lines (0);
    time_reopen (10);
    log_fifo_size (20000);
    use_dns (yes);
    use_fqdn (yes);
    create_dirs (yes);
    dir_group("wheel");
    dir_owner("nobody");
    dir_perm(0755);
    owner("nobody");
    group("nobody");
    perm(0644);

    keep_hostname (yes);

    chain_hostnames(yes);
    bad_hostname("[^[:print:]]");

    dns_cache(yes);
    dns_cache_expire(300);
    dns_cache_expire_failed(30);
    dns_cache_size(1000);

    stats_freq(3600);
    flush_lines(0);
};

#################################################################
#
# source options
#

source s_sys {
    file ("/proc/kmsg" program_override("kernel: "));
    unix-stream ("/dev/log");
    #internal();
    # udp(ip(0.0.0.0) port(514));
};

source s_tcp {
    network(transport("tcp") port(514) so_rcvbuf(8388608) max-connections(200) log-iw-size(20000));
};
source s_udp {
    network(transport("udp") port(514) so_rcvbuf(8388608) log-iw-size(20000));
};

source s_windows {
    network(transport("tcp") port(516) so_rcvbuf(8388608) max-connections(200) log-iw-size(20000));
};

#################################################################
#
# destination options
#

destination d_cons { file("/dev/console"); };
destination d_mesg { file("/var/log/messages"); };
destination d_auth { file("/var/log/secure"); };
destination d_mail { file("/var/log/maillog" flush_lines(10)); };
destination d_spol { file("/var/log/spooler"); };
destination d_boot { file("/var/log/boot.log"); };
destination d_cron { file("/var/log/cron"); };
destination d_kern { file("/var/log/kern"); };
destination d_mlal { usertty("*"); };

destination d_userx { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/user.log"); };
destination d_kernx { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/kern.log"); };
destination d_mailx { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/mail.log"); };
destination d_mp { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/mp.log"); };
destination d_daemonx { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/daemon.log"); };
destination d_authx { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/auth.log"); };
destination d_lprx { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/lpr.log"); };
destination d_cronx { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/cron.log"); };
destination d_messagesx { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/messages.log"); };
destination d_networkx { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/network.log"); };
destination d_firewallx { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/firewall.log"); };
destination d_local0 { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/sp.log"); };
destination d_local1 { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/app.log"); };
destination d_localx { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/local.log"); };
destination d_local6 { file("/mnt/u001/syslog/$HOST/$YEAR$MONTH$DAY/httpd.log"); };

destination d_logstash {
    tcp("127.0.0.1" port(5140)
        template("$R_ISODATE <$FACILITY_NUM.$LEVEL_NUM> $HOST $MSGHDR $MESSAGE\n")
        frac_digits(3) template-escape(no));
    #pipe("/var/log/logstash-pipe"
    #    template("$R_ISODATE <$FACILITY_NUM.$LEVEL_NUM> $HOST $MSGHDR $MESSAGE\n")
    #    frac_digits(3) template-escape(no));
};

# Ingress for network/firewall
destination d_ingress_net {
    pipe("/var/log/ingress-net");
};

# Ingress for windows
destination d_ingress_windows {
    pipe("/var/log/ingress-windows");
};

# Ingress for general
destination d_ingress_general {
    pipe("/var/log/ingress-general");
};

# Stream for InfraDev
destination d_userauth {
    tcp("removed-host1.com" port(13456));
};

# Stream for NetOps
destination d_notifier {
    tcp("removed-host2.com" port(6000));
};



#################################################################
#
# filter options
#

filter f_kernel             { facility(kern); };
filter f_default            { level(info..emerg)
                              and not (facility(mail)
                                  or facility(authpriv) 
                                  or facility(cron))
                              and not message("Syslog connection (accepted|closed)"); };
filter f_auth               { facility(auth,authpriv); };
filter f_mail               { facility(mail); };
filter f_emergency          { level(emerg); };
filter f_news               { facility(uucp) or
                              (facility(news) 
                                  and level(crit..emerg)); };
filter f_boot               { facility(local7); };
filter f_cron               { facility(cron,solaris-cron); };
#
filter f_user               { facility(user); };
filter f_daemon             { facility(daemon); };
filter f_lpr                { facility(lpr); };

filter f_local0             { facility(local0); };
filter f_local1             { facility(local1); };
filter f_local2             { facility(local2); };
filter f_local3             { facility(local3); };
filter f_local4             { facility(local4); };
filter f_local5             { facility(local5); };
filter f_local6             { facility(local6); };
filter f_local7             { facility(local7); };

filter f_alert              { level(alert); };
filter f_crit               { level(crit); };
filter f_err                { level(err); };
filter f_warn               { level(warn); };
filter f_notice             { level(notice); };
filter f_info               { level(info); };
filter f_debug              { level(debug); };
filter f_nonet              { not facility(local4) and not facility(local5); };
filter f_nocf3              { not program("cf3"); };
filter f_nodhcpd            { not program("dhcpd"); };
filter f_windows          { not source(s_windows); };
filter f_snmptrapd          { program("snmptrapd"); };
filter f_userauth           { not facility(local3); };

filter f_notifier_filter    { not match("TRAFFIC|permitted|Deny|Denied|denied", value("MESSAGE")); };

rewrite f_rewrite_name      { set("$FULLHOST_FROM", value("HOST")
                              condition(not source(s_windows)
                                        and not match("REMOTELOG", value("MESSAGE")))); };

rewrite r_snmptrapd         { subst("^([^ ]+) (.*)", "${2}", value("MESSAGE"));
                              set("${1}", value("HOST")); };

#################################################################
#
# log statements
#

### Local system messages
# Uncomment if you want to see kernel messages on the serial console
#log { source(s_sys); filter(f_kernel); destination(d_cons); };
log { source(s_sys); filter(f_kernel); destination(d_kern); };
log { source(s_sys); filter(f_default); destination(d_mesg); };
log { source(s_sys); filter(f_auth); destination(d_auth); };
log { source(s_sys); filter(f_mail); destination(d_mail); };
log { source(s_sys); filter(f_emergency); destination(d_mlal); };
log { source(s_sys); filter(f_news); destination(d_spol); };
log { source(s_sys); filter(f_boot); destination(d_boot); };
log { source(s_sys); filter(f_cron); destination(d_cron); };
log {
    source(s_sys);
    filter(f_snmptrapd);
    rewrite(r_snmptrapd);
    destination(d_networkx);
    destination(d_logstash);
    destination(d_ingress_net);
    log {
    filter(f_notifier_filter);
    destination(d_notifier);
    };
};

### Remote messages
log {
    source(s_udp);
    source(s_tcp);
    source(s_sys);
    source(s_windows);
    log {
        # Log all windows traffic to Ingress without rewriting hostnames
        filter(f_windows);
        destination(d_ingress_windows);
    };
    log {
        # Log all traffic to userauth (infradev) server without rewriting hostnames
        filter(f_userauth);
        destination(d_userauth);
    };
    log {
        rewrite(f_rewrite_name);
        log {
            # Log all traffic to Logstash
            destination(d_logstash);
        };
        log {
            filter(f_nonet);
            filter(f_nocf3);
            filter(f_nodhcpd);
            destination(d_ingress_general);
        };
        log {
            filter(f_user);
            destination(d_userx);
        };
        log {
            filter(f_kernel);
            destination(d_kernx);
        };
        log {
            filter(f_mail);
            destination(d_mailx);
        };
        log {
            filter(f_daemon);
            destination(d_daemonx);
        };
        log {
            filter(f_auth);
            destination(d_authx);
        };
        log {
            filter(f_lpr);
            destination(d_lprx);
        };       
        log {
            filter(f_cron);
            destination(d_cronx);
        };
        log {
            filter(f_local0);
            destination(d_local0);
        }; 
        log {
            filter(f_local1);
            destination(d_local1);
        };                
        log {
            filter(f_local2);
            destination(d_authx);

        };
        log {
            filter(f_local4);
            destination(d_firewallx);
            destination(d_ingress_net);
            log {
                filter(f_notifier_filter);
                destination(d_notifier);
            };
        };        
        log {
            filter(f_local5);
            destination(d_networkx);
            destination(d_ingress_net);
            log {
                filter(f_notifier_filter);
                destination(d_notifier);
            };
        };              
        log {
            filter(f_local6);
            destination(d_local6);

        };
        log {
            filter(f_local7);
            destination(d_mp);
        };
    };
};
```

**Comment by elentar** [comment]
![feb4236e43b8e7bfda33f8073cf9d64f](https://cloud.githubusercontent.com/assets/1018128/6930861/10cad21e-d7bc-11e4-96ff-34c4193d2817.png)

**Comment by deirf** [comment]
We found a similar bug in pe. This is the patch. Maybe help for you.

diff --git a/lib/logwriter.c b/lib/logwriter.c
index 3b7ffe1..8c73b0c 100644
--- a/lib/logwriter.c
+++ b/lib/logwriter.c
@@ -1610,6 +1610,12 @@ log_writer_new(guint32 flags)
   return &self->super;
 }
 
+LogQueue *
+log_writer_get_queue(LogWriter *self)
+{
+  return self->queue;
+}
+
 /* consumes the reference */
 void
 log_writer_set_queue(LogPipe *s, LogQueue *queue)
diff --git a/lib/logwriter.h b/lib/logwriter.h
index 4e823e0..1a54da2 100644
--- a/lib/logwriter.h
+++ b/lib/logwriter.h
@@ -89,6 +89,8 @@ void log_writer_reopen(LogPipe *s, LogProto *proto, LogProtoOptions *proto_optio
 LogPipe *log_writer_new(guint32 flags);
 void log_writer_set_queue(LogPipe *s, LogQueue *queue);
 
+LogQueue *log_writer_get_queue(LogWriter *self);
+
 void log_writer_options_set_template_escape(LogWriterOptions *options, gboolean enable);
 void log_writer_options_defaults(LogWriterOptions *options);
 void log_writer_options_init(LogWriterOptions *options, GlobalConfig *cfg, guint32 option_flags);
diff --git a/modules/affile/affile_common.c b/modules/affile/affile_common.c
index c8185b6..7268dfc 100644
--- a/modules/affile/affile_common.c
+++ b/modules/affile/affile_common.c
@@ -1,4 +1,5 @@
 #include "affile_common.h"
+#include "logwriter.h"
 #include "driver.h"
 #include "messages.h"
 #include "misc.h"
@@ -1256,6 +1257,8 @@ affile_dd_format_persist_name(AFFileDestDriver *self)
 static void
 affile_dd_reap_writer(AFFileDestDriver *self, AFFileDestWriter *dw)
 {
+  LogWriter *writer = (LogWriter *)dw->writer;
+
   main_loop_assert_main_thread();
 
   if ((self->flags & AFFILE_NO_EXPAND) == 0)
@@ -1273,6 +1276,7 @@ affile_dd_reap_writer(AFFileDestDriver *self, AFFileDestWriter *dw)
       g_static_mutex_unlock(&self->lock);
     }
 
+  log_dest_driver_release_queue(&self->super, log_writer_get_queue(writer));
   log_pipe_deinit(&dw->super);
   log_pipe_unref(&dw->super);
 }

**Comment by lbudai** [comment]
Hi,

could you attach some example logs ?

-> what if you set a low value for reap, like this:
```
time_reap(1)
```
(We found a bug which leaks queues and with low reap value memory leaked faster...
The patch above fixes that problem.)

?

**Comment by gregory094** [comment]
The ported patch is available [here](https://github.com/gregory094/syslog-ng/tree/3.6/f/memleak)

**Comment by gregory094** [comment]
Could you give us the number of hosts to calculate the memory assumption?

**Comment by mitzkia** [comment]
I started to reproduce the issue. Using valgrind I got the following output, maybe it can help
```
==31273== 479,752 (79,992 direct, 399,760 indirect) bytes in 9,999 blocks are definitely lost in loss record 3,407 of 3,415
==31273==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==31273==    by 0x5149610: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x515F22D: g_slice_alloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x5117E5A: g_mutex_new (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x51181F4: g_static_mutex_get_mutex_impl (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x4E8D7EE: _late_tracker_lock (late_ack_tracker.c:55)
==31273==    by 0x4E8DACD: late_ack_tracker_request_bookmark (late_ack_tracker.c:156)
==31273==    by 0x4E74072: ack_tracker_request_bookmark (ack_tracker.h:72)
==31273==    by 0x4E74834: log_reader_fetch_log (logreader.c:357)
==31273==    by 0x4E7410E: log_reader_work_perform (logreader.c:86)
==31273==    by 0x4E7CFD7: _work (mainloop-io-worker.c:52)
==31273==    by 0x4EB7746: iv_work_thread_do_work (iv_work.c:118)
==31273== 
==31273== 572,024 (95,384 direct, 476,640 indirect) bytes in 11,923 blocks are definitely lost in loss record 3,408 of 3,415
==31273==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==31273==    by 0x5149610: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x515F22D: g_slice_alloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x5117E5A: g_mutex_new (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x51181F4: g_static_mutex_get_mutex_impl (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x74841BF: affile_dw_queue (affile-dest.c:270)
==31273==    by 0x7483760: log_pipe_queue (logpipe.h:326)
==31273==    by 0x7485058: affile_dd_queue (affile-dest.c:693)
==31273==    by 0x4E6E702: log_pipe_queue (logpipe.h:326)
==31273==    by 0x4E6E93F: log_multiplexer_queue (logmpx.c:106)
==31273==    by 0x4E6E702: log_pipe_queue (logpipe.h:326)
==31273==    by 0x4E6E93F: log_multiplexer_queue (logmpx.c:106)
==31273== 
==31273== 572,176 (95,376 direct, 476,800 indirect) bytes in 11,922 blocks are definitely lost in loss record 3,409 of 3,415
==31273==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==31273==    by 0x5149610: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x515F22D: g_slice_alloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x5117E5A: g_mutex_new (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x51181F4: g_static_mutex_get_mutex_impl (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x4E72468: log_queue_check_items (logqueue.c:96)
==31273==    by 0x4E78E4C: log_writer_update_watches (logwriter.c:438)
==31273==    by 0x4E78FCD: log_writer_start_watches (logwriter.c:501)
==31273==    by 0x4E7B121: log_writer_reopen_deferred (logwriter.c:1353)
==31273==    by 0x4E7C28C: main_loop_call (mainloop-call.c:63)
==31273==    by 0x4E7B166: log_writer_reopen (logwriter.c:1388)
==31273==    by 0x7483DEA: affile_dw_reopen (affile-dest.c:178)
==31273== 
==31273== 10,849,248 bytes in 38,748 blocks are possibly lost in loss record 3,412 of 3,415
==31273==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==31273==    by 0x5149610: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x4E70E5E: log_msg_alloc (logmsg.c:1059)
==31273==    by 0x4E71024: log_msg_clone_cow (logmsg.c:1126)
==31273==    by 0x4E6EF3A: log_msg_make_writable (logmsg.c:225)
==31273==    by 0x4EAC322: log_rewrite_set_process (rewrite-set.c:48)
==31273==    by 0x4EABED8: log_rewrite_queue (rewrite-expr.c:50)
==31273==    by 0x4E6E702: log_pipe_queue (logpipe.h:326)
==31273==    by 0x4E6E93F: log_multiplexer_queue (logmpx.c:106)
==31273==    by 0x4E6E702: log_pipe_queue (logpipe.h:326)
==31273==    by 0x4E6E5FB: log_pipe_forward_msg (logpipe.h:297)
==31273==    by 0x4E6E71B: log_pipe_queue (logpipe.h:330)
==31273== 
==31273== 16,535,256 bytes in 27,204 blocks are possibly lost in loss record 3,413 of 3,415
==31273==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==31273==    by 0x5149610: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x4E800B7: nv_table_realloc (nvtable.c:680)
==31273==    by 0x4E6F8CF: log_msg_set_value (logmsg.c:517)
==31273==    by 0x7482DE8: affile_sd_queue (affile-source.c:327)
==31273==    by 0x4E7569F: log_pipe_queue (logpipe.h:326)
==31273==    by 0x4E75598: log_pipe_forward_msg (logpipe.h:297)
==31273==    by 0x4E76193: log_source_queue (logsource.c:298)
==31273==    by 0x4E73E88: log_pipe_queue (logpipe.h:326)
==31273==    by 0x4E7478C: log_reader_handle_line (logreader.c:320)
==31273==    by 0x4E74944: log_reader_fetch_log (logreader.c:381)
==31273==    by 0x4E7410E: log_reader_work_perform (logreader.c:86)
==31273== 
==31273== 25,611,780 bytes in 38,747 blocks are possibly lost in loss record 3,414 of 3,415
==31273==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==31273==    by 0x5149610: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x4E8029C: nv_table_clone (nvtable.c:734)
==31273==    by 0x4E6F891: log_msg_set_value (logmsg.c:507)
==31273==    by 0x4EAC34A: log_rewrite_set_process (rewrite-set.c:49)
==31273==    by 0x4EABED8: log_rewrite_queue (rewrite-expr.c:50)
==31273==    by 0x4E6E702: log_pipe_queue (logpipe.h:326)
==31273==    by 0x4E6E93F: log_multiplexer_queue (logmpx.c:106)
==31273==    by 0x4E6E702: log_pipe_queue (logpipe.h:326)
==31273==    by 0x4E6E5FB: log_pipe_forward_msg (logpipe.h:297)
==31273==    by 0x4E6E71B: log_pipe_queue (logpipe.h:330)
==31273==    by 0x4E6E5FB: log_pipe_forward_msg (logpipe.h:297)
==31273== 
==31273== 27,567,964 bytes in 38,741 blocks are possibly lost in loss record 3,415 of 3,415
==31273==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==31273==    by 0x5149610: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==31273==    by 0x4E70E5E: log_msg_alloc (logmsg.c:1059)
==31273==    by 0x4E70EEC: log_msg_new (logmsg.c:1084)
==31273==    by 0x4E7474E: log_reader_handle_line (logreader.c:312)
==31273==    by 0x4E74944: log_reader_fetch_log (logreader.c:381)
==31273==    by 0x4E7410E: log_reader_work_perform (logreader.c:86)
==31273==    by 0x4E7CFD7: _work (mainloop-io-worker.c:52)
==31273==    by 0x4EB7746: iv_work_thread_do_work (iv_work.c:118)
==31273==    by 0x4EB6AB2: iv_run_tasks (iv_task.c:48)
==31273==    by 0x4EB8C8B: iv_main (iv_main_posix.c:106)
==31273==    by 0x4EB7593: iv_work_thread (iv_work.c:200)
==31273== 
==31273== LEAK SUMMARY:
==31273==    definitely lost: 272,904 bytes in 33,860 blocks
==31273==    indirectly lost: 1,809,608 bytes in 49,167 blocks
==31273==      possibly lost: 80,577,944 bytes in 143,760 blocks
==31273==    still reachable: 15,716,969 bytes in 47,318 blocks
==31273==         suppressed: 0 bytes in 0 blocks

```

**Comment by mitzkia** [comment]
sorry, but i made a mistake in the previous valgrind check, this is the correct valgrind output
```
==19774== 480,352 (80,072 direct, 400,280 indirect) bytes in 10,009 blocks are definitely lost in loss record 3,023 of 3,029
==19774==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19774==    by 0x5149610: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==19774==    by 0x515F22D: g_slice_alloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==19774==    by 0x5117E5A: g_mutex_new (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==19774==    by 0x51181F4: g_static_mutex_get_mutex_impl (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==19774==    by 0x4E8D7EE: _late_tracker_lock (late_ack_tracker.c:55)
==19774==    by 0x4E8DACD: late_ack_tracker_request_bookmark (late_ack_tracker.c:156)
==19774==    by 0x4E74072: ack_tracker_request_bookmark (ack_tracker.h:72)
==19774==    by 0x4E74834: log_reader_fetch_log (logreader.c:357)
==19774==    by 0x4E7410E: log_reader_work_perform (logreader.c:86)
==19774==    by 0x4E7CFD7: _work (mainloop-io-worker.c:52)
==19774==    by 0x4EB7746: iv_work_thread_do_work (iv_work.c:118)
==19774== 
==19774== 622,824 (103,824 direct, 519,000 indirect) bytes in 12,978 blocks are definitely lost in loss record 3,026 of 3,029
==19774==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19774==    by 0x5149610: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==19774==    by 0x515F22D: g_slice_alloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==19774==    by 0x5117E5A: g_mutex_new (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==19774==    by 0x51181F4: g_static_mutex_get_mutex_impl (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==19774==    by 0x4E72468: log_queue_check_items (logqueue.c:96)
==19774==    by 0x4E78E4C: log_writer_update_watches (logwriter.c:438)
==19774==    by 0x4E78FCD: log_writer_start_watches (logwriter.c:501)
==19774==    by 0x4E7B121: log_writer_reopen_deferred (logwriter.c:1353)
==19774==    by 0x4E7C28C: main_loop_call (mainloop-call.c:63)
==19774==    by 0x4E7B166: log_writer_reopen (logwriter.c:1388)
==19774==    by 0x7483DEA: affile_dw_reopen (affile-dest.c:178)
==19774== 
==19774== 622,896 (103,816 direct, 519,080 indirect) bytes in 12,977 blocks are definitely lost in loss record 3,027 of 3,029
==19774==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19774==    by 0x5149610: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==19774==    by 0x515F22D: g_slice_alloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==19774==    by 0x5117E5A: g_mutex_new (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==19774==    by 0x51181F4: g_static_mutex_get_mutex_impl (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0)
==19774==    by 0x74841BF: affile_dw_queue (affile-dest.c:270)
==19774==    by 0x7483760: log_pipe_queue (logpipe.h:326)
==19774==    by 0x7485058: affile_dd_queue (affile-dest.c:693)
==19774==    by 0x4E6E702: log_pipe_queue (logpipe.h:326)
==19774==    by 0x4E6E93F: log_multiplexer_queue (logmpx.c:106)
==19774==    by 0x4E6E702: log_pipe_queue (logpipe.h:326)
==19774==    by 0x4E6E93F: log_multiplexer_queue (logmpx.c:106)
==19774== 
==19774== LEAK SUMMARY:
==19774==    definitely lost: 291,528 bytes in 36,044 blocks
==19774==    indirectly lost: 1,898,799 bytes in 51,435 blocks
==19774==      possibly lost: 1,416 bytes in 13 blocks
==19774==    still reachable: 15,183,534 bytes in 43,903 blocks
==19774==         suppressed: 0 bytes in 0 blocks

```

**Comment by elentar** [comment]
gregory094, this server acts as a default for when we don't have a better destination, such as for various desktop systems and the like. It could potentially have 4000+ hosts sending to it, but most likely it would only be 500-1000 systems. Most of the traffic comes from a dozen or so network firewalls.

**Comment by elentar** [comment]
mitzkia, I tried using valgrind on the process but had trouble getting it to actually process logs when running under valgrind. Can you share the command you used? I can do that on my server to see what it reports.

**Comment by mitzkia** [comment]
@elentar , of course, I used the following command: 
sudo valgrind -v --log-file=valgrind.log --leak-check=full sbin/syslog-ng -F -f etc/syslog-ng-leak.conf --enable-core

It would be very usefull if you also can send a valgrind output.

**Comment by elentar** [comment]
I'm running the valgrind command. After 5 minutes or so, I still haven't see any log messages actually processed, but we'll see if it just needs more time...

**Comment by elentar** [comment]
Well, ran for about an hour and processed around 115,000 messages.

```
==22141== LEAK SUMMARY:
==22141==    definitely lost: 768 bytes in 7 blocks
==22141==    indirectly lost: 2,790 bytes in 32 blocks
==22141==      possibly lost: 2,291,678 bytes in 3,474 blocks
==22141==    still reachable: 210,416 bytes in 3,838 blocks
==22141==         suppressed: 0 bytes in 0 blocks
==22141== Reachable blocks (those to which a pointer was found) are not shown.
==22141== To see them, rerun with: --leak-check=full --show-reachable=yes
==22141== 
==22141== Use --track-origins=yes to see where uninitialised values come from
==22141== ERROR SUMMARY: 338 errors from 64 contexts (suppressed: 6 from 6)
```

**Comment by elentar** [comment]
There was no significant consumption of memory during this test. I'll try again with the time_reap(1) option.

**Comment by mitzkia** [comment]
@elentar  After you tried with time_reap(1) could you copy-paste the most significant leaks what valgrind finds. It is right before the "Leak Summary" line. Thanks.

**Comment by lbudai** [comment]
@mitzkia : what is your configuration?

**Comment by mitzkia** [comment]
I am using this config:
```
@version:3.6

# vim:ft=syslog-ng:ai:si:ts=4:sw=4:et:

#################################################################
# syslog-ng configuration file.
#
# global options
#
# See syslog-ng(8) and syslog-ng.conf(5) for more information.
#

options {
    flush_lines (0);
    time_reopen (10);
    time_reap(1);
    log_fifo_size (20000);
    use_dns (yes);
    use_fqdn (yes);
    create_dirs (yes);
    dir_group("wheel");
    dir_owner("nobody");
    dir_perm(0755);
    owner("nobody");
    group("nobody");
    perm(0644);

    keep_hostname (no);

    chain_hostnames(yes);
    bad_hostname("[^[:print:]]");

    dns_cache(yes);
    dns_cache_expire(300);
    dns_cache_expire_failed(30);
    dns_cache_size(1000);

    stats_freq(3600);
    flush_lines(0);
};

#################################################################
#
# source options
#

source s_sys {
    file ("/tmp/inputfile2.txt" program_override("kernel: ") keep-timestamp(no));
};

source s_tcp {
    network(transport("tcp") port(514) so_rcvbuf(8388608) max-connections(200) log-iw-size(20000));
};
source s_udp {
    network(transport("udp") port(514) so_rcvbuf(8388608) log-iw-size(20000));
};

source s_windows {
    network(transport("tcp") port(516) so_rcvbuf(8388608) max-connections(200) log-iw-size(20000));
};

#################################################################
#
# destination options
#

destination d_cons { file("/dev/console"); };
destination d_mesg { file("/tmp/micek/messages"); };
destination d_auth { file("/tmp/micek/secure"); };
destination d_mail { file("/tmp/micek/maillog" flush_lines(10)); };
destination d_spol { file("/tmp/micek/spooler"); };
destination d_boot { file("/tmp/micek/boot.log"); };
destination d_cron { file("/tmp/micek/cron"); };
destination d_kern { file("/tmp/micek/kern"); };
#destination d_mlal { usertty("*"); };

destination d_userx { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/user.log"); };
destination d_kernx { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/kern.log"); };
destination d_mailx { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/mail.log"); };
destination d_mp { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/mp.log"); };
destination d_daemonx { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/daemon.log"); };
destination d_authx { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/auth.log"); };
destination d_lprx { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/lpr.log"); };
destination d_cronx { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/cron.log"); };
destination d_messagesx { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/messages.log"); };
destination d_networkx { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/network.log"); };
destination d_firewallx { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/firewall.log"); };
destination d_local0 { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/sp.log"); };
destination d_local1 { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/app.log"); };
destination d_localx { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/local.log"); };
destination d_local6 { file("/tmp/micek/$HOST/$YEAR$MONTH$DAY$HOUR$MIN/httpd.log"); };

destination d_logstash {
    tcp("127.0.0.1" port(5140)
        template("$R_ISODATE <$FACILITY_NUM.$LEVEL_NUM> $HOST $MSGHDR $MESSAGE\n")
        frac_digits(3) template-escape(no));
    #pipe("/tmp/micek/logstash-pipe"
    #    template("$R_ISODATE <$FACILITY_NUM.$LEVEL_NUM> $HOST $MSGHDR $MESSAGE\n")
    #    frac_digits(3) template-escape(no));
};

# Ingress for network/firewall
destination d_ingress_net {
    pipe("/tmp/micek/ingress-net");
};

# Ingress for windows
destination d_ingress_windows {
    pipe("/tmp/micek/ingress-windows");
};

# Ingress for general
destination d_ingress_general {
    pipe("/tmp/micek/ingress-general");
};

# Stream for InfraDev
destination d_userauth {
    tcp("127.0.0.1" port(13456));
};

# Stream for NetOps
destination d_notifier {
    tcp("127.0.0.1" port(6000));
};



#################################################################
#
# filter options
#

filter f_kernel             { facility(kern); };
filter f_default            { level(info..emerg)
                              and not (facility(mail)
                                  or facility(authpriv) 
                                  or facility(cron))
                              and not message("Syslog connection (accepted|closed)"); };
filter f_auth               { facility(auth,authpriv); };
filter f_mail               { facility(mail); };
filter f_emergency          { level(emerg); };
filter f_news               { facility(uucp) or
                              (facility(news) 
                                  and level(crit..emerg)); };
filter f_boot               { facility(local7); };
filter f_cron               { facility(cron,solaris-cron); };
#
filter f_user               { facility(user); };
filter f_daemon             { facility(daemon); };
filter f_lpr                { facility(lpr); };

filter f_local0             { facility(local0); };
filter f_local1             { facility(local1); };
filter f_local2             { facility(local2); };
filter f_local3             { facility(local3); };
filter f_local4             { facility(local4); };
filter f_local5             { facility(local5); };
filter f_local6             { facility(local6); };
filter f_local7             { facility(local7); };

filter f_alert              { level(alert); };
filter f_crit               { level(crit); };
filter f_err                { level(err); };
filter f_warn               { level(warn); };
filter f_notice             { level(notice); };
filter f_info               { level(info); };
filter f_debug              { level(debug); };
filter f_nonet              { not facility(local4) and not facility(local5); };
filter f_nocf3              { not program("cf3"); };
filter f_nodhcpd            { not program("dhcpd"); };
filter f_windows          { not source(s_windows); };
filter f_snmptrapd          { program("snmptrapd"); };
filter f_userauth           { not facility(local3); };

filter f_notifier_filter    { not match("TRAFFIC|permitted|Deny|Denied|denied", value("MESSAGE")); };

rewrite f_rewrite_name      { set("$FULLHOST_FROM", value("HOST")
                              condition(not source(s_windows)
                                        and not match("REMOTELOG", value("MESSAGE")))); };

rewrite r_snmptrapd         { subst("^([^ ]+) (.*)", "${2}", value("MESSAGE"));
                              set("${1}", value("HOST")); };

#################################################################
#
# log statements
#

### Local system messages
# Uncomment if you want to see kernel messages on the serial console
log { source(s_sys); filter(f_kernel); destination(d_cons); };
log { source(s_sys); filter(f_kernel); destination(d_kern); };
log { source(s_sys); filter(f_default); destination(d_mesg); };
log { source(s_sys); filter(f_auth); destination(d_auth); };
log { source(s_sys); filter(f_mail); destination(d_mail); };
#log { source(s_sys); filter(f_emergency); destination(d_mlal); };
log { source(s_sys); filter(f_news); destination(d_spol); };
log { source(s_sys); filter(f_boot); destination(d_boot); };
log { source(s_sys); filter(f_cron); destination(d_cron); };
log {
    source(s_sys);
    filter(f_snmptrapd);
    rewrite(r_snmptrapd);
    destination(d_networkx);
    destination(d_logstash);
    destination(d_ingress_net);
    log {
    filter(f_notifier_filter);
    destination(d_notifier);
    };
};

### Remote messages
log {
    source(s_udp);
    source(s_tcp);
    source(s_sys);
    source(s_windows);
    log {
        # Log all windows traffic to Ingress without rewriting hostnames
        filter(f_windows);
        destination(d_ingress_windows);
    };
    log {
        # Log all traffic to userauth (infradev) server without rewriting hostnames
        filter(f_userauth);
        destination(d_userauth);
    };
    log {
        rewrite(f_rewrite_name);
        log {
            # Log all traffic to Logstash
            destination(d_logstash);
        };
        log {
            filter(f_nonet);
            filter(f_nocf3);
            filter(f_nodhcpd);
            destination(d_ingress_general);
        };
        log {
            filter(f_user);
            destination(d_userx);
        };
        log {
            filter(f_kernel);
            destination(d_kernx);
        };
        log {
            filter(f_mail);
            destination(d_mailx);
        };
        log {
            filter(f_daemon);
            destination(d_daemonx);
        };
        log {
            filter(f_auth);
            destination(d_authx);
        };
        log {
            filter(f_lpr);
            destination(d_lprx);
        };       
        log {
            filter(f_cron);
            destination(d_cronx);
        };
        log {
            filter(f_local0);
            destination(d_local0);
        }; 
        log {
            filter(f_local1);
            destination(d_local1);
        };                
        log {
            filter(f_local2);
            destination(d_authx);

        };
        log {
            filter(f_local4);
            destination(d_firewallx);
            destination(d_ingress_net);
            log {
                filter(f_notifier_filter);
                destination(d_notifier);
            };
        };        
        log {
            filter(f_local5);
            destination(d_networkx);
            destination(d_ingress_net);
            log {
                filter(f_notifier_filter);
                destination(d_notifier);
            };
        };              
        log {
            filter(f_local6);
            destination(d_local6);

        };
        log {
            filter(f_local7);
            destination(d_mp);
        };
    };
};

```

**Comment by elentar** [comment]
```
==27356== 92,752 bytes in 187 blocks are possibly lost in loss record 761 of 765
==27356==    at 0x4A05588: memalign (vg_replace_malloc.c:727)
==27356==    by 0x4A05623: posix_memalign (vg_replace_malloc.c:876)
==27356==    by 0x3CCC85E777: ??? (in /lib64/libglib-2.0.so.0.2800.8)
==27356==    by 0x3CCC85F031: g_slice_alloc (in /lib64/libglib-2.0.so.0.2800.8)
==27356==    by 0x3CCC83E0A2: g_list_append (in /lib64/libglib-2.0.so.0.2800.8)
==27356==    by 0x4C5EF5E: scratch_buffers_register (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C5EFA6: scratch_buffers_init (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C3F8F8: app_thread_start (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C8080B: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C829EE: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x3CCD4079D0: start_thread (in /lib64/libpthread-2.12.so)
==27356==    by 0x3CCCCE89DC: clone (in /lib64/libc-2.12.so)
==27356== 
==27356== 2,232,716 bytes in 3,265 blocks are possibly lost in loss record 764 of 765
==27356==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==27356==    by 0x3CCC849CD4: g_malloc (in /lib64/libglib-2.0.so.0.2800.8)
==27356==    by 0x4C4EFF3: log_msg_new_empty (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C4F0CE: log_msg_new_internal (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C593AB: msg_send_formatted_message (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C594B4: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x56FADD4: ??? (in /usr/lib64/syslog-ng/libafsocket-tls.so)
==27356==    by 0x4C51096: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C58D11: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C80E85: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C7F925: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C81158: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356== 
==27356== 2,236,136 bytes in 3,270 blocks are possibly lost in loss record 765 of 765
==27356==    at 0x4A06A2E: malloc (vg_replace_malloc.c:270)
==27356==    by 0x3CCC849CD4: g_malloc (in /lib64/libglib-2.0.so.0.2800.8)
==27356==    by 0x4C4EFF3: log_msg_new_empty (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C4F0CE: log_msg_new_internal (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C593AB: msg_send_formatted_message (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C594B4: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x56FA797: ??? (in /usr/lib64/syslog-ng/libafsocket-tls.so)
==27356==    by 0x4C81816: iv_fd_poll_and_run (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C81FD3: iv_main (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x4C57545: main_loop_run (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==27356==    by 0x40194C: main (in /usr/sbin/syslog-ng)
==27356== 
==27356== LEAK SUMMARY:
==27356==    definitely lost: 768 bytes in 7 blocks
==27356==    indirectly lost: 2,790 bytes in 32 blocks
==27356==      possibly lost: 4,753,722 bytes in 7,116 blocks
==27356==    still reachable: 390,808 bytes in 4,149 blocks
==27356==         suppressed: 0 bytes in 0 blocks
==27356== Reachable blocks (those to which a pointer was found) are not shown.
==27356== To see them, rerun with: --leak-check=full --show-reachable=yes
==27356== 
==27356== Use --track-origins=yes to see where uninitialised values come from
==27356== ERROR SUMMARY: 928 errors from 64 contexts (suppressed: 6 from 6)
```

**Comment by elentar** [comment]
Still no appreciable memory loss under valgrind. I'm now running normally to see if I observe that.

**Comment by elentar** [comment]
I've discovered that most of the traffic has been shifted off of this server, so the log volume isn't high enough to cause this issue. I'm sending a duplicate stream from the current destination to this host and will report results.

**Comment by elentar** [comment]
Unable to reproduce the memory issue so far. Will keep trying tomorrow.

**Comment by bazsi** [comment]
Hi,

Just a quick note that PR #447 should contain a related fix, at least the valgrind indicated leaks by @mitzkia should be fixed by that.

**Comment by elentar** [comment]
This issue still occurs, but I have not been able to capture it under valgrind. When running under valgrind, syslog-ng processes only about half the message volume; presumably the rest of the incoming traffic gets dropped. It currently takes around 12 hours before we see the memory leak start to manifest, with traffic around 6000+ msgs/second.

pmap reports that the syslog-ng process has many allocations like this:

```00007f7d3c000000  65536K rw---    [ anon ]```

If the only way to figure this out is to run valgrind for 24+ hours and lose half my messages, I'd prefer to investigate other options first.

**Comment by bazsi** [comment]
Thanks. that allocation above seems to be a heap arena. I have recently investigated a memory consumption situation myself and couldn't find an actual leak using valgrind. What helped in my case tremendously was using jemalloc as an LD_PRELOAD-ed library. I am not sure what causes the libc allocator to start eating memory, further investigation would be needed (and I am not saying it's not a bug in syslog-ng itself).

Anyway, if you can please try jemalloc, this way (on my Ubuntu system):
```
# apt-get install libjemalloc1
# LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so
# <start syslog-ng>
```

Your problem might be unrelated though, but hope this helps.

PS: I'm thinking about reviving the built-in memory allocator debugger in syslog-ng, but that was broken for a long time now. But that's much faster than using valgrind and doesn't require any external libraries. Or find another well-maintained memory profiler that could help.

**Comment by elentar** [comment]
I ran over the weekend under valgrind. The system lost around 3GB of memory before I killed it. I will attach the valgrind output in case it helps anyone, but it doesn't seem to show anything helpful.

Perhaps this is not a classic memory leak but rather just some internal buffer or cache that grows without bound?

**Comment by elentar** [comment]
Apparently I can't attach text files.

```
==22780== 49,600 bytes in 100 blocks are possibly lost in loss record 768 of 783
==22780==    at 0x4C26588: memalign (vg_replace_malloc.c:727)
==22780==    by 0x4C26623: posix_memalign (vg_replace_malloc.c:876)
==22780==    by 0x595A777: ??? (in /lib64/libglib-2.0.so.0.2800.8)
==22780==    by 0x595B031: g_slice_alloc (in /lib64/libglib-2.0.so.0.2800.8)
==22780==    by 0x5960C4A: g_string_sized_new (in /lib64/libglib-2.0.so.0.2800.8)
==22780==    by 0x4E6D4A9: log_writer_new (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x85E7FE2: ??? (in /usr/lib64/syslog-ng/libaffile.so)
==22780==    by 0x85E8919: ??? (in /usr/lib64/syslog-ng/libaffile.so)
==22780==    by 0x4E70EF5: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E98925: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E9A158: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E9A816: iv_fd_poll_and_run (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780== 
==22780== 900,412 bytes in 1,381 blocks are possibly lost in loss record 777 of 783
==22780==    at 0x4C27A2E: malloc (vg_replace_malloc.c:270)
==22780==    by 0x5945CD4: g_malloc (in /lib64/libglib-2.0.so.0.2800.8)
==22780==    by 0x4E67FF3: log_msg_new_empty (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E680CE: log_msg_new_internal (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E723AB: msg_send_formatted_message (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E724B4: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x87FB797: ??? (in /usr/lib64/syslog-ng/libafsocket-tls.so)
==22780==    by 0x4E9A816: iv_fd_poll_and_run (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E9AFD3: iv_main (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E70545: main_loop_run (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x40194C: main (in /usr/sbin/syslog-ng)
==22780== 
==22780== 900,412 bytes in 1,381 blocks are possibly lost in loss record 778 of 783
==22780==    at 0x4C27A2E: malloc (vg_replace_malloc.c:270)
==22780==    by 0x5945CD4: g_malloc (in /lib64/libglib-2.0.so.0.2800.8)
==22780==    by 0x4E67FF3: log_msg_new_empty (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E680CE: log_msg_new_internal (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E723AB: msg_send_formatted_message (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E724B4: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x87FBDD4: ??? (in /usr/lib64/syslog-ng/libafsocket-tls.so)
==22780==    by 0x4E6A096: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E71D11: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E99E85: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E98925: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780==    by 0x4E9A158: ??? (in /usr/lib64/libsyslog-ng-3.6.so.0.0.0)
==22780== 
==22780== LEAK SUMMARY:
==22780==    definitely lost: 856 bytes in 7 blocks
==22780==    indirectly lost: 3,943 bytes in 43 blocks
==22780==      possibly lost: 2,048,436 bytes in 3,231 blocks
==22780==    still reachable: 281,549,615 bytes in 444,623 blocks
==22780==         suppressed: 0 bytes in 0 blocks
==22780== Reachable blocks (those to which a pointer was found) are not shown.
==22780== To see them, rerun with: --leak-check=full --show-reachable=yes
```

**Comment by elentar** [comment]
Running under jemalloc, will report stats.

**Comment by elentar** [comment]
Ran for about a day before syslog-ng dumped core, so I wasn't able to gather statistics from jemalloc.

**Comment by elentar** [comment]
I'm giving up on 3.6, it's entirely too unstable. Perhaps this will get better with 3.7 but for now I'll use 3.5 with the missing source stats, and will look at other software to replace syslog-ng in the longer term.

**Comment by bazsi** [comment]
Sorry to hear. I know that tracking down bugs can be frustrating and I
really appreciate the effort you put into it. Do you perhaps have info
during the 1 day runtime of syslog-ng? did it grow?

We could perhaps help you somewhat more if we could log into the system,
perhaps analyse its behaviour. Are you open to that?

thanks


-- 
Bazsi

**Comment by elentar** [comment]
![e237cf3d40299660fb06b25e6bac2e04](https://cloud.githubusercontent.com/assets/1018128/7149107/5786ba80-e2be-11e4-8a25-8149c8bd4128.png)

**Comment by elentar** [comment]
Attached an image. Ran over the weekend under valgrind through 4/12, then switched to jemalloc until this morning when it crashed.

**Comment by bazsi** [comment]
You injected jemalloc under valgrind?

-- 
Bazsi

**Comment by elentar** [comment]
No, I killed valgrind and restarted syslog-ng under jemalloc pretty much as you recommended except to define the MALLOC_CONF environment variable so I would get a stats printout. Unfortunately, I didn't get to see the stats due to the core dump.

I have been testing this on a production syslog server, which unfortunately means losing logs when syslog-ng dies. Since I can't keep doing that, I'm going to try to create the same issue by replying logs or generating them. If that works, I can gather better data or help someone get remote access, etc.

**Comment by bazsi** [comment]
Thanks a lot. Do you haopen to have a core for the crash?

**Comment by elentar** [comment]
I do. It's 800MB. Here's the bt:

```
(gdb) bt
#0  0x00007fc2594d1625 in raise () from /lib64/libc.so.6
#1  0x00007fc2594d2e05 in abort () from /lib64/libc.so.6
#2  0x00007fc25a7fcc6b in iv_fatal () from /usr/lib64/libsyslog-ng-3.6.so.0
#3  0x00007fc25a7feb2a in iv_fd_init () from /usr/lib64/libsyslog-ng-3.6.so.0
#4  0x00007fc25a7ff099 in iv_init () from /usr/lib64/libsyslog-ng-3.6.so.0
#5  0x00007fc25a7fd78e in ?? () from /usr/lib64/libsyslog-ng-3.6.so.0
#6  0x00007fc25a7ff9ef in ?? () from /usr/lib64/libsyslog-ng-3.6.so.0
#7  0x00007fc25983a9d1 in start_thread () from /lib64/libpthread.so.0
#8  0x00007fc2595878fd in clone () from /lib64/libc.so.6
(gdb) 
```

**Comment by bazsi** [comment]
hmm... somewhat difficult to analyse without symbols. the abort string
would also help, but anyway here's what I have found:

* this is a new thread, probably a worker thread
* it aborts the entire process in ivykis (the event dispatching library we
use)
* iv_fd_init() can abort in two cases
   1) when it fails to identify the polling method to use (this only runs
in the initial thread, so it cannot be ours, being in a worker thread
already)
   2) when the concrete poll implementation fails to initialize in the new
thread

I am assuming you use epoll, RH 6 should be recent enough to have that. In
that case iv_fd_epoll_init() is failing.

epoll_fd_init() only fails if the epoll_create() system call fails. The man
page documents these error cases (although I am sure there can be more):

       EMFILE The per-user limit on the number of epoll instances imposed
by /proc/sys/fs/epoll/max_user_instances was encountered.  See epoll(7) for
further details.

       ENFILE The system limit on the total number of open files has been
reached.

       ENOMEM There was insufficient memory to create the kernel object.


Based on this, I see the following alternatives:

1) your leak is not just memory, but also fd leak. And you are hitting the
fd limit (1024 by default). It might happen that we don't close files for
some reason (one of the patches posted in the series was exactly fixing
such an issue). Can you please check if syslog-ng keeps opened a lot of
files that it should have closed already? lsof -p <pid> should display the
list of files. Did you apply the quoted patch?

2) you are hitting /proc/sys/fs/epoll/max_user_instances, but that's a
pretty high number on my 64 bit computer, and I see from the backtrace that
yours is 64 bit too. Can you check that value just to be sure?

3) some other error occurs when we call epoll_create(). I don't see what it
can be though and I would probably need an access to a core file/binaries
to analyse.

Hope this helps.


-- 
Bazsi

**Comment by elentar** [comment]
I've only seen the crash when running under jemalloc; under normal operation it just runs out of memory. Once we have a test instance I can try to test further.

**Comment by bazsi** [comment]
Lsof on the production instance should not interfere with logging.

**Comment by lbudai** [comment]
Today we've found something... 

1. if internal messages are not processed (via `internal()` source) AND syslog-ng started in foreground mode without `-e` then we leak lots of messages  (`log_msg_new_internal` )

Just use `internal()` source.

2. when a filename in a file destination contains a macro, we found a huge memleak
case a) macros in filenames
![image](https://cloud.githubusercontent.com/assets/5908786/7412872/10738c46-ef47-11e4-8885-3752fe533d3d.png)

case b) filenames without macros
![image](https://cloud.githubusercontent.com/assets/5908786/7412885/30c8d384-ef47-11e4-8aff-6b90630dc2d7.png)

A new PR is address this issue: #473

Could you test the patch?

**Comment by elentar** [comment]
We definitely use macros in filenames; thousands of files get written using them. I'll put some work into building a new version with this to test it out.

-Pradeep

**Comment by lbudai** [comment]
I've merged PR #473 into 3.6/master.
You can use that branch.
If you need help in building syslog-ng from source, just contact us.

**Comment by lbudai** [comment]
any update?

**Comment by elentar** [comment]
So far the memory issue has not re-occurred. I see the process use about 3GB of ram and then level out. I'll want to run longer to be sure but it does look promising.

Graph attached. Process was restarted where the vertical jumps occur.
 

-Pradeep

**Comment by ihrwein** [comment]
@elentar it seems like GitHub doesn't support attached images via e-mail. Could you upload it to somewhere?

**Comment by elentar** [comment]
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/1018128/7520815/2bdac1be-f507-11e4-9047-ee3632df393b.png)

**Comment by johntdyer** [comment]
Is there any ETA on when 3.6.3 will drop ?

**Comment by lbudai** [comment]
Hi,

within a few days (we have two PRs and an issue what we want to check).

**Comment by lbudai** [comment]
hmm... I didn't want to close it...

**Comment by ihrwein** [comment]
@johntdyer You can download the `3.6.3` release from here: https://github.com/balabit/syslog-ng/releases

I'm closing this ticket since the original issue is solved.

@elentar Many thanks for the great cooperation!
