### ISSUE TITLE
format-json produces invalid json

### ISSUE THREAD

**Issue by bobrik** [balabit/syslog-ng#999]
syslog-ng 3.7.2, template looks like this:

```
$(format-json @timestamp=\"$ISODATE\" logsource=\"$HOST\" program=\"$PROGRAM\" message=\"$MESSAGE\" app=\"something\")
```

This produces the following JSON messages (one per line):

``` json
{"program":"ÿ¿¿¿¿¾3m5","logsource":"a.b.c","app":"nginx","@timestamp":"2016-03-24T16:03:24+00
{"program":"mcmd\\xf4\\xf5\\xefά","logsource":"a.b.c","app":"nginx","@timestamp":"2016-03-24T16:03:24+00:00"}
```

Might be somehow connected to #917, as it is observed in the same installation.

**Comment by bkil-syslogng** [comment]
Could you please test with 3.7.3 or git master as well?

**Comment by bobrik** [comment]
3.7.3 has the same issue.

**Comment by bkil-syslogng** [comment]
I've tested the given template format both from the command line and in a sterile unit testing environment and it works for me in both cases.

We would need more information on the kind of input you feed this template with and a full configuration file as well. It would help a lot if you could minimize them.

**Comment by bobrik** [comment]
Main pipeline sends logs to kafka, but I also steered logs from problematic host to output JSON on stdout too:

```
destination d_debug { file("/dev/stdout" template("$(format-json @timestamp=\"$ISODATE\" logsource=\"$HOST\" program=\"$PROGRAM\" message=\"$MESSAGE\" app=\"nginx\")\n")); };

filter f_hehe { host("hehe"); };

log {
    source(s_net);
    filter(f_hehe);
    destination(d_debug);
};
```

This does not reveal messages with truncated JSON.

Kafka:

```
{"program":"nginx","message":"\\xafcac\\xfb\\xb2\\xcdά","logsource":"hehe","app":"nginx","@timestamp":"2016-04-02T15:35:00+00:00"}
{"program":"nginx","message":"ÿ¿¿¿¿¾\\xfb\\xb2\\xcdά","logsource":"hehe","app":"nginx","@timestamp":"2016-04-02T15:35:00+00
```

Stdout:

```
2016-04-02T18:01:06.000 myhost {"program":"nginx","message":"\\xafcac\\xfb\\xb2\\xcdά","logsource":"hehe","app":"nginx","@timestamp":"2016-04-02T15:35:00+00:00"}
2016-04-02T18:01:06.000 myhost {"program":"nginx","message":"������\\xfb\\xb2\\xcdά","logsource":"hehe","app":"nginx","@timestamp":"2016-04-02T15:35:00+00:00"}
```

I suspect that something goes south between syslog-ng and JVM. Running `strace` on `syslog-ng` shows that it indeed sends truncated data to JVM. I'll try to get access to the machine that produces this garbage, to see what's getting send. It's hard to debug it from receiving side with `tls` transport.

On a related note, setting `sanitize-utf8` flag consistently core dumped JVM. Unicode handling bothers me, since JSON looks different in kafka and it stdout. It could be due to the fact that stdout logs are not strictly stdout, they flow through another logging pipeline too. Maybe doing proper encoding with `\uXXXX` could help.

Hopefully this helps.

**Comment by erempel** [comment]
This issue is around Unicode log lines. It seems that the json output is truncated to the number of bytes that matches the number characters in the log line, but some of the characters are more than 1 byte.

**Comment by lbudai** [comment]
#1088 should solve this... 
@erempel : did it solve your problem?

**Comment by erempel** [comment]
No, I still have the same issue. The log shows that the content of the json object was faulty. The json object was NOT created on this host. it was created on a different host and passed as the MESSAGE of the syslog event. When recieved, this message is logged to a text file where it is complete, and passed to elasticsearch with a template("$MESSAGE") option. It is the elasticsearch driver that seems to truncate the json object.

failed to execute bulk item (index) index {[flare-2016.07.05.09][flare][AVW7z9ph56hU5fHmicJi], source[{"year":"2016","flare":{"profile":"DCS-Windows"},"cfgmgrrole":"ADMIN","cfgmgrosFull":"Windows 2012 R2 Standard","cfgmgros":"windows","cfgmgrmodel":"ESX 5","cfgmgrlocation":"ESX-BCP","cfgmgrenvironment":"BCP PROD","cfgmgrassetType":"Virtual Server","SOURCEHOST":"madtom.uvic.ca","SHORTHOST":"madtom","PROGRAM":"ExchTrack","PRIORITY":"info","PID":"2940","PATTERNID":"3187","MESSAGE":"2016-07-05T16:06:48.490Z,1.1.1.1,uaru.uvic.ca,2.2.2.2,madtom,08D3972BD771A4E1;2016-07-05T16:06:48.323Z;0,MADTOM\\Default MADTOM,SMTP,RECEIVE,73997991543608,<D3A127AC.4E80C%user@uvic.ca>,99e26ed6-67b4-4ba3-b012-08d3a4ee5e90,other@shaw.ca,,8954,1,,,Re: Unicode subject Franch ð<U+009F><U+0091><U+0091>ð<U+009F><U+0092><U+008B>ð<U+009F><U+0091><U+009B>ð<U+009F><U+0091><U+0093>ð<U+009F><U+0099>
<U+008A>ð<U+009F><U+0099><U+0088>ð<U+009F>¦<U+0084>ð<U+009F><U+0090> ð<U+009F><U+0090>²,user@uvic.ca,user@uvic.ca,0cI: ,Originating,,3.3.3.3,4.4.4.4,S:FirstForestHop=mail.uvic.ca;S:DeliveryPriority=Normal;S:AccountForest=uvic.ca","ISODATE":"2016-07-05T09:06:48.000-07:00","HOST":"madtom.uvic.ca","FACILITY":]}

**Comment by gaborznagy** [comment]
Hi @erempel, do you still have this problem?
